import type { CommissionerAuditSource } from '@prisma/client';
import { validateContractConfig } from '@fhm/engine';
import { prisma } from '../db/client.js';
import { canonicalContractConfig, hashContractConfig } from './contract-config.js';
import { ContractHttpError } from './contract-errors.js';

async function audit(entityType:any,entityId:string,action:any,reason:string,before:unknown,after:unknown,source:CommissionerAuditSource){await prisma.commissionerAuditLog.create({data:{entityType,entityId,action,reason,beforeJson:JSON.stringify(before),afterJson:JSON.stringify(after),changedFieldsJson:JSON.stringify(['contractSystem']),source}});}
export async function auditContractAction(entityType:any,entityId:string,action:any,reason:string,after:unknown,source:CommissionerAuditSource){return audit(entityType,entityId,action,reason,null,after,source);}
export async function createContractPreset(input:{name:string;description?:string|null;config:unknown;activate?:boolean;reason:string},source:CommissionerAuditSource){const config=validateContractConfig(input.config);if(await prisma.contractPreset.findUnique({where:{name:input.name}}))throw new ContractHttpError(409,'ContractConfigurationConflict','Configuration name already exists');const preset=await prisma.contractPreset.create({data:{name:input.name,description:input.description,isSystem:false,versions:{create:{versionNumber:1,schemaVersion:1,configJson:canonicalContractConfig(config),configHash:hashContractConfig(config),changeReason:input.reason,createdBySource:source}}},include:{versions:true}});await audit('CONTRACT_CONFIG',preset.id,'CONTRACT_CONFIG_CREATED',input.reason,null,{name:preset.name},source);if(input.activate)await activateContractVersion(preset.versions[0]!.id,input.reason,source);return preset;}
export async function createContractVersion(presetId:string,input:{config:unknown;activate?:boolean;reason:string},source:CommissionerAuditSource){const config=validateContractConfig(input.config),preset=await prisma.contractPreset.findUnique({where:{id:presetId},include:{versions:{orderBy:{versionNumber:'desc'},take:1}}});if(!preset)throw new ContractHttpError(404,'ContractConfigurationNotFound','Configuration not found');const version=await prisma.contractPresetVersion.create({data:{presetId,versionNumber:(preset.versions[0]?.versionNumber??0)+1,schemaVersion:1,configJson:canonicalContractConfig(config),configHash:hashContractConfig(config),changeReason:input.reason,createdBySource:source}});await audit('CONTRACT_CONFIG',version.id,'CONTRACT_CONFIG_VERSION_CREATED',input.reason,null,{presetId,versionNumber:version.versionNumber},source);if(input.activate)await activateContractVersion(version.id,input.reason,source);return version;}
export async function activateContractVersion(versionId:string,reason:string,source:CommissionerAuditSource){const version=await prisma.contractPresetVersion.findUnique({where:{id:versionId}});if(!version)throw new ContractHttpError(404,'ContractConfigurationNotFound','Configuration version not found');const before=await prisma.activeContractConfiguration.findUnique({where:{id:'default'}});const active=await prisma.activeContractConfiguration.upsert({where:{id:'default'},create:{id:'default',activePresetVersionId:versionId},update:{activePresetVersionId:versionId}});await audit('CONTRACT_CONFIG',versionId,'CONTRACT_CONFIG_ACTIVATED',reason,before,active,source);return active;}
