import type { ContractOfferType, CommissionerAuditSource, Prisma } from '@prisma/client';
import {
  assertRightsConversion, assertSigningEligibility, classifyExpiration, isDerivedFreeAgent,
  recommendContract, recommendExtension, stableContractHash, validateOfferTerms,
  type ContractPlayerInput,
} from '@fhm/engine';
import { prisma } from '../db/client.js';
import { compactPlayerModelFields, derivePublicPlayerModel } from './player-model.js';
import { getActiveContractSnapshot } from './contract-config.js';
import { ContractHttpError } from './contract-errors.js';
import { createContractTransaction } from './contract-transactions.js';
import { createSqliteSafetyBackup } from './sqlite-backup.js';

const playerInclude={nationality:true,currentTeam:true,skaterAttributes:true,goalieAttributes:true,contracts:true,contractOffers:{select:{id:true,status:true}},draftRights:{where:{status:'ACTIVE'}},scoutingReports:{orderBy:{versionNumber:'desc'}}} as const;
type LoadedPlayer=Prisma.PlayerGetPayload<{include:typeof playerInclude}>;
const fullName=(p:{firstName:string;lastName:string})=>`${p.firstName} ${p.lastName}`;
const seasonDate=(startYear:number)=>`${startYear}-09-15`;
const seasonDto=(s:{id:string;label:string;startYear:number;endYear:number})=>({id:s.id,label:s.label,order:s.startYear,startYear:s.startYear,endYear:s.endYear});
const updatedIso=(d:Date)=>d.toISOString();

function stripAttributes(row:Record<string,unknown>|null){if(!row)return null;const{playerId:_p,createdAt:_c,updatedAt:_u,...attrs}=row;return attrs as Record<string,number>;}
function publicModelRow(p:LoadedPlayer){return{primaryPosition:p.primaryPosition,preferredCoachingStyle:p.preferredCoachingStyle,preferredTactics:p.preferredTactics,personality:p.personality,heroRating:p.heroRating,stability:p.stability,developmentRate:p.developmentRate,developmentRisk:p.developmentRisk,potentialFloor:p.potentialFloor,potentialCeiling:p.potentialCeiling,publicPotentialEstimate:p.publicPotentialEstimate,skaterAttributes:stripAttributes(p.skaterAttributes),goalieAttributes:stripAttributes(p.goalieAttributes)};}

function scoutingAbility(p:LoadedPlayer,teamId?:string|null):number|null{if(!teamId)return null;const row=p.scoutingReports.find(r=>r.teamId===teamId);if(!row)return null;try{const report=JSON.parse(row.reportJson);return typeof report?.currentAbility?.estimate==='number'?report.currentAbility.estimate:null;}catch{return null;}}

function contractPlayerInput(p:LoadedPlayer,effectiveYear:number,teamId?:string|null):ContractPlayerInput{
  const derived=derivePublicPlayerModel(publicModelRow(p));
  const active=p.contracts.find(c=>c.status==='ACTIVE'),future=p.contracts.some(c=>c.status==='FUTURE');
  const ability=p.rosterStatus==='PROSPECT'?(scoutingAbility(p,teamId)??40):(derived?.ratings.currentAbility??40);
  return{playerId:p.id,dateOfBirth:p.dateOfBirth.toISOString().slice(0,10),effectiveDate:seasonDate(effectiveYear),currentAbility:ability,roleRating:derived?.ratings.roleRating??null,recentPerformance:null,developmentTrend:null,rosterStatus:p.rosterStatus,currentTeamId:p.currentTeamId,activeContractTeamId:active?.teamId??null,hasFutureContract:future,activeDraftRightTeamId:p.draftRights[0]?.teamId??null,currentAnnualSalary:active?.annualSalary??null};
}

function mapContract(c:any){return{id:c.id,playerId:c.playerId,teamId:c.teamId,player:c.player?{id:c.player.id,name:fullName(c.player),position:c.player.primaryPosition}:undefined,team:c.team?{id:c.team.id,name:c.team.name}:undefined,startSeason:c.startWorldSeason?seasonDto(c.startWorldSeason):{id:c.startWorldSeasonId,order:c.startSeasonOrderSnapshot},endSeason:c.endWorldSeason?seasonDto(c.endWorldSeason):{id:c.endWorldSeasonId,order:c.endSeasonOrderSnapshot},annualSalary:c.annualSalary,status:c.status,contractType:c.contractType,source:c.source,signedAt:c.signedAt,activatedAt:c.activatedAt,expiredAt:c.expiredAt,terminatedAt:c.terminatedAt,playerNameSnapshot:c.playerNameSnapshot,teamNameSnapshot:c.teamNameSnapshot,termsHash:c.termsHash,updatedAt:c.updatedAt};}
const contractFullInclude={player:true,team:true,startWorldSeason:true,endWorldSeason:true,originatingOffer:true,originatingDraftRight:{include:{draftEvent:true,draftPick:true}},transactions:{orderBy:{createdAt:'desc'}},recommendations:{orderBy:{createdAt:'desc'}}} as const;

export async function getContractsStatus(){const [meta,active,openOffers,freeAgents,rightsHeld]=await Promise.all([prisma.appMeta.findUnique({where:{id:'default'}}),prisma.playerContract.count({where:{status:'ACTIVE'}}),prisma.contractOffer.count({where:{status:'SUBMITTED'}}),deriveFreeAgentCount(),prisma.playerDraftRight.count({where:{status:'ACTIVE'}})]);return{initialized:Boolean(meta?.contractsInitializedAt),initializedAt:meta?.contractsInitializedAt??null,activeContracts:active,openOffers,freeAgents,rightsHeldUnsignedProspects:rightsHeld,noSalaryCap:true};}
async function deriveFreeAgentCount(){return prisma.player.count({where:{currentTeamId:null,rosterStatus:{not:'RETIRED'},contracts:{none:{status:{in:['ACTIVE','FUTURE']}}},draftRights:{none:{status:'ACTIVE'}}}});}

export async function listContracts(query:any={}){const page=Math.max(1,Number(query.page)||1),pageSize=Math.min(100,Math.max(1,Number(query.pageSize)||25));const where:any={};if(query.teamId)where.teamId=query.teamId;if(query.playerId)where.playerId=query.playerId;if(query.status)where.status=query.status;if(query.source)where.source=query.source;if(query.endSeasonOrder)where.endSeasonOrderSnapshot=Number(query.endSeasonOrder);const [total,items]=await Promise.all([prisma.playerContract.count({where}),prisma.playerContract.findMany({where,include:{player:true,team:true,startWorldSeason:true,endWorldSeason:true},orderBy:[{endSeasonOrderSnapshot:'asc'},{createdAt:'desc'}],skip:(page-1)*pageSize,take:pageSize})]);return{items:items.map(mapContract),meta:{page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};}
export async function getContract(id:string){const row=await prisma.playerContract.findUnique({where:{id},include:contractFullInclude});if(!row)throw new ContractHttpError(404,'ContractNotFound','Contract not found');return{...mapContract(row),originatingOffer:row.originatingOffer,draftRight:row.originatingDraftRight,transactions:row.transactions,recommendations:row.recommendations};}
export async function getPlayerContractStatus(playerId:string){const p=await prisma.player.findUnique({where:{id:playerId},include:{contracts:{include:{team:true,startWorldSeason:true,endWorldSeason:true},orderBy:{createdAt:'desc'}},draftRights:{where:{status:'ACTIVE'},include:{team:true}}}});if(!p)throw new ContractHttpError(404,'PlayerNotFound','Player not found');const active=p.contracts.find(c=>c.status==='ACTIVE'),future=p.contracts.find(c=>c.status==='FUTURE');return{playerId,currentTeamId:p.currentTeamId,activeContract:active?mapContract(active):null,futureContract:future?mapContract(future):null,isFreeAgent:p.rosterStatus!=='RETIRED'&&!p.currentTeamId&&!active&&!future&&!p.draftRights.length,rightsRestriction:p.draftRights[0]?{teamId:p.draftRights[0].teamId,teamName:p.draftRights[0].team.name}:null};}
export async function getPlayerContracts(playerId:string){const exists=await prisma.player.findUnique({where:{id:playerId},select:{id:true}});if(!exists)throw new ContractHttpError(404,'PlayerNotFound','Player not found');return listContracts({playerId,pageSize:100});}
export async function getPlayerRecommendations(playerId:string){return{items:await prisma.contractRecommendation.findMany({where:{playerId},orderBy:{createdAt:'desc'},include:{team:true}})};}
export async function getPlayerOffers(playerId:string){return{items:await prisma.contractOffer.findMany({where:{playerId},orderBy:{createdAt:'desc'},include:{offeringTeam:true,startWorldSeason:true,endWorldSeason:true}})};}
export async function getPlayerTransactions(playerId:string){return{items:await prisma.contractTransaction.findMany({where:{playerId},orderBy:{createdAt:'desc'}})};}
export async function getTeamContracts(teamId:string){const team=await prisma.team.findUnique({where:{id:teamId}});if(!team)throw new ContractHttpError(404,'TeamNotFound','Team not found');const result=await listContracts({teamId,pageSize:100});return{...result,payroll:result.items.filter((c:any)=>c.status==='ACTIVE').reduce((n:number,c:any)=>n+c.annualSalary,0),salaryCapEnforced:false};}
export async function getTeamExpiring(teamId:string,seasonOrder?:number){const season=seasonOrder??(await currentSeason()).startYear;return{items:(await listContracts({teamId,status:'ACTIVE',endSeasonOrder:season,pageSize:100})).items};}
export async function getTeamOffers(teamId:string){return{items:await prisma.contractOffer.findMany({where:{offeringTeamId:teamId},include:{player:true,startWorldSeason:true,endWorldSeason:true},orderBy:{createdAt:'desc'}})};}
async function currentSeason(){return(await prisma.worldSeason.findFirst({where:{status:'ACTIVE'},orderBy:{startYear:'asc'}}))??(await prisma.worldSeason.findFirst({orderBy:{startYear:'asc'}}))??(()=>{throw new ContractHttpError(422,'ContractSigningNotReady','No WorldSeason exists')})();}

export async function listFreeAgents(query:any={}){const page=Math.max(1,Number(query.page)||1),pageSize=Math.min(100,Math.max(1,Number(query.pageSize)||25)),teamId=query.teamId||null;const where:any={currentTeamId:null,rosterStatus:{not:'RETIRED'},contracts:{none:{status:{in:['ACTIVE','FUTURE']}}},draftRights:{none:{status:'ACTIVE'}}};if(query.position)where.primaryPosition=query.position;const [total,season,players,config]=await Promise.all([prisma.player.count({where}),currentSeason(),prisma.player.findMany({where,include:playerInclude,orderBy:[{lastName:'asc'},{firstName:'asc'}],skip:(page-1)*pageSize,take:pageSize}),getActiveContractSnapshot(prisma)]);return{items:players.map(p=>{const input=contractPlayerInput(p,season.startYear,teamId),rec=recommendContract(input,config.config),model=p.rosterStatus==='PROSPECT'?{modelStatus:'SCOUTING_REQUIRED',currentAbility:teamId?input.currentAbility:null,role:null,roleRating:null,publicPotentialEstimate:'UNKNOWN'}:compactPlayerModelFields(publicModelRow(p));return{player:{id:p.id,name:fullName(p),position:p.primaryPosition,country:p.nationality.name,rosterStatus:p.rosterStatus,model},previousContract:p.contracts.filter(c=>c.status==='EXPIRED'||c.status==='TERMINATED').sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime())[0]??null,recommendation:{annualSalary:rec.recommendedAnnualSalary,termYears:rec.recommendedTermYears,confidence:rec.recommendationConfidence},openOffers:p.contractOffers.filter(o=>o.status==='DRAFT'||o.status==='SUBMITTED').length,eligibleToSign:true,rightsRestriction:null};}),meta:{page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};}
export async function getFreeAgent(playerId:string,teamId?:string){const list=await listFreeAgents({teamId,pageSize:100});const item=list.items.find(i=>i.player.id===playerId);if(!item)throw new ContractHttpError(409,'PlayerNotFreeAgent','Player is not an unrestricted free agent');return item;}

export async function createRecommendation(teamId:string,playerId:string){const [p,team,season,activeConfig]=await Promise.all([prisma.player.findUnique({where:{id:playerId},include:playerInclude}),prisma.team.findUnique({where:{id:teamId}}),currentSeason(),getActiveContractSnapshot(prisma)]);if(!p)throw new ContractHttpError(404,'PlayerNotFound','Player not found');if(!team)throw new ContractHttpError(404,'TeamNotFound','Team not found');const input=contractPlayerInput(p,season.startYear,teamId);const current=p.contracts.find(c=>c.status==='ACTIVE')??null;const result=current?recommendExtension(input,activeConfig.config):{...recommendContract(input,activeConfig.config),recommendationType:'REVIEW' as const};const inputHash=stableContractHash(input);const row=await prisma.contractRecommendation.create({data:{playerId,teamId,currentContractId:current?.id??null,recommendationType:result.recommendationType,recommendedSalary:result.recommendedAnnualSalary,recommendedTermYears:result.recommendedTermYears,factorsText:JSON.stringify(result.factors),configVersionId:activeConfig.version.id,configHash:activeConfig.version.configHash,inputHash,recommendationHash:result.recommendationHash}});return{...row,factors:result.factors};}

export async function createOffer(teamId:string,input:{playerId:string;offerType:ContractOfferType;startWorldSeasonId:string;endWorldSeasonId:string;annualSalary:number;reason?:string;draftRightId?:string;currentContractId?:string}){const [p,team,start,end,activeConfig,season]=await Promise.all([prisma.player.findUnique({where:{id:input.playerId},include:playerInclude}),prisma.team.findUnique({where:{id:teamId}}),prisma.worldSeason.findUnique({where:{id:input.startWorldSeasonId}}),prisma.worldSeason.findUnique({where:{id:input.endWorldSeasonId}}),getActiveContractSnapshot(prisma),currentSeason()]);if(!p)throw new ContractHttpError(404,'PlayerNotFound','Player not found');if(!team)throw new ContractHttpError(404,'TeamNotFound','Team not found');if(!start||!end)throw new ContractHttpError(422,'InvalidContractTerms','Contract seasons do not exist');try{assertSigningEligibility(contractPlayerInput(p,season.startYear,teamId),input.offerType,teamId);validateOfferTerms({offerType:input.offerType,offeringTeamId:teamId,startSeason:{id:start.id,order:start.startYear},endSeason:{id:end.id,order:end.startYear},annualSalary:input.annualSalary},activeConfig.config,p.contracts.map(c=>({id:c.id,startOrder:c.startSeasonOrderSnapshot,endOrder:c.endSeasonOrderSnapshot,status:c.status})).filter(c=>(c.status==='ACTIVE'||c.status==='FUTURE')&&(input.offerType!=='EXTENSION'||c.status!=='ACTIVE')));}catch(e:any){throw new ContractHttpError(e.name==='InvalidContractTerms'?422:409,e.name,e.message);}
  const openOffers=p.contractOffers.filter(o=>o.status==='DRAFT'||o.status==='SUBMITTED').length;if(openOffers>=activeConfig.config.offers.maximumOpenOffersPerPlayer)throw new ContractHttpError(409,'MaximumOpenOffersReached','The player already has the configured maximum number of open offers');
  if(input.offerType!=='EXTENSION'&&start.startYear!==season.startYear)throw new ContractHttpError(422,'ContractSigningNotReady','Free-agent and rights contracts must start in the current existing WorldSeason');
  const current=p.contracts.find(c=>c.status==='ACTIVE');if(input.offerType==='EXTENSION'&&(!current||start.startYear!==current.endSeasonOrderSnapshot+1))throw new ContractHttpError(422,'InvalidContractTerms','Extension must start in the season immediately following the active contract');
  const right=input.offerType==='DRAFT_RIGHTS'?p.draftRights.find(r=>r.id===input.draftRightId):undefined;if(input.offerType==='DRAFT_RIGHTS'&&!right)throw new ContractHttpError(409,'DraftRightRequired','The specified active draft right is required');
  const stateHash=stableContractHash({playerId:p.id,updatedAt:p.updatedAt.toISOString(),currentTeamId:p.currentTeamId,activeContractId:current?.id??null,futureContractId:p.contracts.find(c=>c.status==='FUTURE')?.id??null,rightId:right?.id??null,rightStatus:right?.status??null});const termsHash=stableContractHash({playerId:p.id,teamId,start:start.id,end:end.id,salary:input.annualSalary,type:input.offerType});
  return prisma.contractOffer.create({data:{playerId:p.id,offeringTeamId:teamId,offerType:input.offerType,targetContractType:input.offerType==='DRAFT_RIGHTS'?'ENTRY':'STANDARD',startWorldSeasonId:start.id,endWorldSeasonId:end.id,annualSalary:input.annualSalary,currentContractId:input.offerType==='EXTENSION'?current!.id:null,draftRightId:right?.id??null,configVersionId:activeConfig.version.id,configHash:activeConfig.version.configHash,playerStateHash:stateHash,termsHash,expiresAtSeasonOrder:end.startYear+activeConfig.config.offers.offerExpirationSeasonOffset,reason:input.reason}});
}

async function assertOfferWrite(offerId:string,teamId:string|undefined,expectedUpdatedAt?:string){const offer=await prisma.contractOffer.findUnique({where:{id:offerId}});if(!offer)throw new ContractHttpError(404,'ContractOfferNotFound','Contract offer not found');if(teamId&&offer.offeringTeamId!==teamId)throw new ContractHttpError(404,'ContractOfferNotFound','Contract offer not found for this team');if(expectedUpdatedAt&&updatedIso(offer.updatedAt)!==new Date(expectedUpdatedAt).toISOString())throw new ContractHttpError(409,'DevelopmentInputStale','Offer was modified by another action');return offer;}
export async function submitOffer(offerId:string,teamId:string,expectedUpdatedAt?:string){const offer=await assertOfferWrite(offerId,teamId,expectedUpdatedAt);if(offer.status!=='DRAFT')throw new ContractHttpError(409,'OfferNotEditable','Only draft offers can be submitted');return prisma.contractOffer.update({where:{id:offer.id},data:{status:'SUBMITTED',submittedAt:new Date()}});}
export async function withdrawOffer(offerId:string,teamId:string,reason:string,expectedUpdatedAt?:string){const offer=await assertOfferWrite(offerId,teamId,expectedUpdatedAt);if(!['DRAFT','SUBMITTED'].includes(offer.status))throw new ContractHttpError(409,'OfferNotEditable','Offer cannot be withdrawn');return prisma.$transaction(async tx=>{const updated=await tx.contractOffer.update({where:{id:offer.id},data:{status:'WITHDRAWN',withdrawnAt:new Date(),reason}});const p=await tx.player.findUniqueOrThrow({where:{id:offer.playerId}}),t=await tx.team.findUniqueOrThrow({where:{id:offer.offeringTeamId}});await createContractTransaction(tx,{transactionType:'OFFER_WITHDRAWN',playerId:p.id,teamId:t.id,offerId:offer.id,playerNameSnapshot:fullName(p),teamNameSnapshot:t.name,reason,source:'LOCAL_TEAM'});return updated;});}

export async function rejectOffer(offerId:string,reason:string,expectedUpdatedAt?:string){const offer=await assertOfferWrite(offerId,undefined,expectedUpdatedAt);if(offer.status!=='SUBMITTED')throw new ContractHttpError(409,'OfferNotEditable','Only submitted offers can be rejected');return prisma.$transaction(async tx=>{const updated=await tx.contractOffer.update({where:{id:offer.id},data:{status:'REJECTED',rejectedAt:new Date(),reason}});const p=await tx.player.findUniqueOrThrow({where:{id:offer.playerId}}),t=await tx.team.findUniqueOrThrow({where:{id:offer.offeringTeamId}});await createContractTransaction(tx,{transactionType:'OFFER_REJECTED',playerId:p.id,teamId:t.id,offerId:offer.id,playerNameSnapshot:fullName(p),teamNameSnapshot:t.name,reason,source:'LOCAL_ACTION'});return updated;});}

export async function acceptOffer(offerId:string,reason:string,expectedUpdatedAt?:string){const snapshot=await assertOfferWrite(offerId,undefined,expectedUpdatedAt);if(snapshot.status!=='SUBMITTED')throw new ContractHttpError(409,snapshot.status==='ACCEPTED'?'OfferAlreadyAccepted':'OfferNotEditable','Only a submitted offer can be accepted');return prisma.$transaction(async tx=>{const offer=await tx.contractOffer.findUniqueOrThrow({where:{id:offerId},include:{player:{include:{contracts:true,draftRights:{where:{status:'ACTIVE'}}}},offeringTeam:true,startWorldSeason:true,endWorldSeason:true}});if(offer.status!=='SUBMITTED')throw new ContractHttpError(409,'CompetingOfferAlreadyAccepted','Offer is no longer actionable');const current=offer.player.contracts.find(c=>c.status==='ACTIVE'),future=offer.player.contracts.find(c=>c.status==='FUTURE');if(offer.offerType==='EXTENSION'){if(!current||current.id!==offer.currentContractId||current.teamId!==offer.offeringTeamId||future)throw new ContractHttpError(409,'ContractOverlap','Extension state changed');}else{if(current||future||offer.player.currentTeamId)throw new ContractHttpError(409,'PlayerAlreadyUnderContract','Player signed elsewhere');if(offer.offerType==='DRAFT_RIGHTS'){const right=offer.player.draftRights.find(r=>r.id===offer.draftRightId);if(!right)throw new ContractHttpError(409,'DraftRightAlreadyConverted','Draft right is no longer active');try{assertRightsConversion({rightStatus:right.status,rightTeamId:right.teamId,signingTeamId:offer.offeringTeamId,playerCurrentTeamId:offer.player.currentTeamId});}catch(e:any){throw new ContractHttpError(409,e.name,e.message);}}else if(offer.player.draftRights.length)throw new ContractHttpError(409,'DraftRightOwnedByAnotherTeam','Player has active draft rights');}
    const status=offer.offerType==='EXTENSION'?'FUTURE':'ACTIVE';const now=new Date();const contract=await tx.playerContract.create({data:{playerId:offer.playerId,teamId:offer.offeringTeamId,startWorldSeasonId:offer.startWorldSeasonId,endWorldSeasonId:offer.endWorldSeasonId,startSeasonOrderSnapshot:offer.startWorldSeason.startYear,endSeasonOrderSnapshot:offer.endWorldSeason.startYear,annualSalary:offer.annualSalary,status,contractType:offer.targetContractType,source:offer.offerType==='EXTENSION'?'EXTENSION':offer.offerType==='DRAFT_RIGHTS'?'DRAFT_RIGHTS':'FREE_AGENT',activatedAt:status==='ACTIVE'?now:null,supersedesContractId:offer.offerType==='EXTENSION'?current!.id:null,originatingOfferId:offer.id,originatingDraftRightId:offer.draftRightId,configVersionId:offer.configVersionId,configHash:offer.configHash,playerNameSnapshot:fullName(offer.player),teamNameSnapshot:offer.offeringTeam.name,termsHash:offer.termsHash}});
    await tx.contractOffer.update({where:{id:offer.id},data:{status:'ACCEPTED',acceptedAt:now,reason}});await tx.contractOffer.updateMany({where:{playerId:offer.playerId,id:{not:offer.id},status:'SUBMITTED'},data:{status:'REJECTED',rejectedAt:now,reason:'Competing offer closed after signing'}});if(status==='ACTIVE')await tx.player.update({where:{id:offer.playerId},data:{currentTeamId:offer.offeringTeamId}});if(offer.offerType==='DRAFT_RIGHTS')await tx.playerDraftRight.update({where:{id:offer.draftRightId!},data:{status:'CONVERTED_TO_CONTRACT'}});
    await createContractTransaction(tx,{transactionType:offer.offerType==='EXTENSION'?'EXTENSION_SIGNED':offer.offerType==='DRAFT_RIGHTS'?'DRAFT_RIGHTS_SIGNED':'FREE_AGENT_SIGNED',playerId:offer.playerId,teamId:offer.offeringTeamId,contractId:contract.id,offerId:offer.id,draftRightId:offer.draftRightId,playerNameSnapshot:fullName(offer.player),teamNameSnapshot:offer.offeringTeam.name,termsSnapshotText:JSON.stringify({start:offer.startWorldSeason.label,end:offer.endWorldSeason.label,annualSalary:offer.annualSalary}),reason,source:'LOCAL_ACTION'});return mapContract({...contract,player:offer.player,team:offer.offeringTeam,startWorldSeason:offer.startWorldSeason,endWorldSeason:offer.endWorldSeason});});}

export async function releaseContract(contractId:string,teamId:string|undefined,input:{reason:string;expectedUpdatedAt?:string}){const contract=await prisma.playerContract.findUnique({where:{id:contractId},include:{player:true,team:true}});if(!contract)throw new ContractHttpError(404,'ContractNotFound','Contract not found');if(teamId&&contract.teamId!==teamId)throw new ContractHttpError(404,'ContractNotFound','Contract not found for this team');if(contract.status!=='ACTIVE')throw new ContractHttpError(409,'ActiveContractNotFound','Only an active contract can be released');if(input.expectedUpdatedAt&&updatedIso(contract.updatedAt)!==new Date(input.expectedUpdatedAt).toISOString())throw new ContractHttpError(409,'DevelopmentInputStale','Contract was modified');if(await prisma.playerContract.count({where:{playerId:contract.playerId,status:'FUTURE'}}))throw new ContractHttpError(409,'FutureContractExists','Cancel the future contract before release');return prisma.$transaction(async tx=>{const now=new Date();const updated=await tx.playerContract.update({where:{id:contract.id},data:{status:'TERMINATED',terminatedAt:now}});await tx.player.update({where:{id:contract.playerId},data:{currentTeamId:null}});await createContractTransaction(tx,{transactionType:'PLAYER_RELEASED',playerId:contract.playerId,teamId:contract.teamId,contractId:contract.id,playerNameSnapshot:fullName(contract.player),teamNameSnapshot:contract.team.name,termsSnapshotText:JSON.stringify({annualSalary:contract.annualSalary}),reason:input.reason,source:teamId?'LOCAL_TEAM':'COMMISSIONER'});return updated;});}

async function initialCandidates(worldSeasonId:string){const season=await prisma.worldSeason.findUnique({where:{id:worldSeasonId}});if(!season)throw new ContractHttpError(404,'WorldSeasonNotFound','WorldSeason not found');const [players,config]=await Promise.all([prisma.player.findMany({where:{currentTeamId:{not:null},rosterStatus:{not:'RETIRED'},contracts:{none:{status:{in:['ACTIVE','FUTURE']}}}},include:playerInclude,orderBy:{id:'asc'}}),getActiveContractSnapshot(prisma)]);const rows=players.map(p=>{const rec=recommendContract(contractPlayerInput(p,season.startYear,p.currentTeamId),config.config);return{player:p,annualSalary:rec.recommendedAnnualSalary,termsHash:stableContractHash({playerId:p.id,teamId:p.currentTeamId,seasonId:season.id,annualSalary:rec.recommendedAnnualSalary})};});return{season,config,rows,inputHash:stableContractHash(rows.map(r=>({playerId:r.player.id,teamId:r.player.currentTeamId,salary:r.annualSalary,termsHash:r.termsHash})))};}
export async function previewInitialContracts(worldSeasonId:string){const meta=await prisma.appMeta.findUnique({where:{id:'default'}});if(meta?.contractsInitializedAt)throw new ContractHttpError(409,'ContractsAlreadyInitialized','Contracts are already initialized');const data=await initialCandidates(worldSeasonId);return{worldSeason:seasonDto(data.season),totalContracts:data.rows.length,annualSalaryTotal:data.rows.reduce((n,r)=>n+r.annualSalary,0),inputHash:data.inputHash,items:data.rows.map(r=>({playerId:r.player.id,playerName:fullName(r.player),teamId:r.player.currentTeamId,teamName:r.player.currentTeam?.name,annualSalary:r.annualSalary,startWorldSeasonId:data.season.id,endWorldSeasonId:data.season.id}))};}
export async function prepareInitialContracts(worldSeasonId:string,reason:string,createdBy:string){const preview=await previewInitialContracts(worldSeasonId),config=await getActiveContractSnapshot(prisma);const existing=await prisma.contractInitializationRun.findFirst({where:{status:'PREPARED'}});if(existing)throw new ContractHttpError(409,'InitialContractsAlreadyPrepared','An initialization run is already prepared');return prisma.contractInitializationRun.create({data:{worldSeasonId,status:'PREPARED',inputHash:preview.inputHash,totalContracts:preview.totalContracts,annualSalaryTotal:preview.annualSalaryTotal,configVersionId:config.version.id,reason,createdBy}});}
export async function executeInitialContracts(runId:string){const run=await prisma.contractInitializationRun.findUnique({where:{id:runId}});if(!run)throw new ContractHttpError(404,'ContractInitializationRunNotFound','Initialization run not found');if(run.status==='COMPLETED')return run;if(run.status!=='PREPARED')throw new ContractHttpError(409,'ContractInitializationNotPrepared','Initialization run is not prepared');const data=await initialCandidates(run.worldSeasonId);if(data.inputHash!==run.inputHash)throw new ContractHttpError(409,'DevelopmentInputStale','Initialization inputs changed');await createSqliteSafetyBackup({label:`contracts-initial-${run.id}`});return prisma.$transaction(async tx=>{const created=[] as any[];for(const r of data.rows){const team=r.player.currentTeam!;const contract=await tx.playerContract.create({data:{playerId:r.player.id,teamId:team.id,startWorldSeasonId:data.season.id,endWorldSeasonId:data.season.id,startSeasonOrderSnapshot:data.season.startYear,endSeasonOrderSnapshot:data.season.startYear,annualSalary:r.annualSalary,status:'ACTIVE',contractType:'STANDARD',source:'INITIAL_IMPORT',activatedAt:new Date(),configVersionId:data.config.version.id,configHash:data.config.version.configHash,playerNameSnapshot:fullName(r.player),teamNameSnapshot:team.name,termsHash:r.termsHash}});await createContractTransaction(tx,{transactionType:'INITIAL_CONTRACT',playerId:r.player.id,teamId:team.id,contractId:contract.id,effectiveWorldSeasonId:data.season.id,playerNameSnapshot:fullName(r.player),teamNameSnapshot:team.name,termsSnapshotText:JSON.stringify({annualSalary:r.annualSalary,season:data.season.label}),reason:run.reason,source:'COMMISSIONER_BATCH'});created.push(contract.id);}const resultHash=stableContractHash(created.sort());await tx.appMeta.update({where:{id:'default'},data:{contractsInitializedAt:new Date()}});return tx.contractInitializationRun.update({where:{id:run.id},data:{status:'COMPLETED',completedAt:new Date(),resultHash}});});}

export async function expirationPreview(worldSeasonId:string){const season=await prisma.worldSeason.findUnique({where:{id:worldSeasonId}});if(!season)throw new ContractHttpError(404,'WorldSeasonNotFound','WorldSeason not found');const contracts=await prisma.playerContract.findMany({where:{status:{in:['ACTIVE','FUTURE']}},include:{player:true,team:true},orderBy:{playerId:'asc'}});const active=contracts.filter(c=>c.status==='ACTIVE');const decisions=active.map(c=>{const f=contracts.find(x=>x.playerId===c.playerId&&x.status==='FUTURE');return classifyExpiration({id:c.id,playerId:c.playerId,teamId:c.teamId,startOrder:c.startSeasonOrderSnapshot,endOrder:c.endSeasonOrderSnapshot,status:'ACTIVE'},f?{id:f.id,playerId:f.playerId,teamId:f.teamId,startOrder:f.startSeasonOrderSnapshot,endOrder:f.endSeasonOrderSnapshot,status:'FUTURE'}:undefined,season.startYear)});const actionable=decisions.filter(d=>d.action!=='NONE');return{worldSeason:seasonDto(season),effectiveSeasonOrder:season.startYear,totalContracts:actionable.length,expiredCount:actionable.length,activatedFutureCount:actionable.filter(d=>d.action==='EXPIRE_AND_ACTIVATE_FUTURE').length,freeAgentCount:actionable.filter(d=>d.action==='EXPIRE_TO_FREE_AGENT').length,inputHash:stableContractHash(actionable),items:actionable};}
export async function prepareExpiration(worldSeasonId:string,reason:string,createdBy:string){const preview=await expirationPreview(worldSeasonId),config=await getActiveContractSnapshot(prisma);const completed=await prisma.contractExpirationRun.findFirst({where:{worldSeasonId,status:'COMPLETED'}});if(completed)return completed;const prepared=await prisma.contractExpirationRun.findFirst({where:{worldSeasonId,status:'PREPARED'}});if(prepared)return prepared;return prisma.contractExpirationRun.create({data:{worldSeasonId,effectiveSeasonOrder:preview.effectiveSeasonOrder,status:'PREPARED',inputHash:preview.inputHash,totalContracts:preview.totalContracts,configVersionId:config.version.id,reason,createdBy}});}
export async function executeExpiration(runId:string){const run=await prisma.contractExpirationRun.findUnique({where:{id:runId}});if(!run)throw new ContractHttpError(404,'ContractExpirationRunNotFound','Expiration run not found');if(run.status==='COMPLETED')return run;if(run.status!=='PREPARED')throw new ContractHttpError(409,'ContractExpirationAlreadyProcessed','Expiration run is not prepared');const preview=await expirationPreview(run.worldSeasonId);if(preview.inputHash!==run.inputHash)throw new ContractHttpError(409,'DevelopmentInputStale','Expiration inputs changed');await createSqliteSafetyBackup({label:`contracts-expiration-${run.id}`});return prisma.$transaction(async tx=>{for(const d of preview.items){const old=await tx.playerContract.findUniqueOrThrow({where:{id:d.contractId},include:{player:true,team:true}});await tx.playerContract.update({where:{id:old.id},data:{status:'EXPIRED',expiredAt:new Date()}});await createContractTransaction(tx,{transactionType:'CONTRACT_EXPIRED',playerId:old.playerId,teamId:old.teamId,contractId:old.id,expirationRunId:run.id,effectiveWorldSeasonId:run.worldSeasonId,playerNameSnapshot:fullName(old.player),teamNameSnapshot:old.team.name,reason:run.reason,source:'COMMISSIONER_BATCH'});if(d.action==='EXPIRE_AND_ACTIVATE_FUTURE'){const future=await tx.playerContract.update({where:{id:d.futureContractId!},data:{status:'ACTIVE',activatedAt:new Date()}});await tx.player.update({where:{id:old.playerId},data:{currentTeamId:future.teamId}});await createContractTransaction(tx,{transactionType:'FUTURE_CONTRACT_ACTIVATED',playerId:old.playerId,teamId:future.teamId,contractId:future.id,expirationRunId:run.id,effectiveWorldSeasonId:run.worldSeasonId,playerNameSnapshot:fullName(old.player),teamNameSnapshot:old.team.name,reason:run.reason,source:'COMMISSIONER_BATCH'});}else await tx.player.update({where:{id:old.playerId},data:{currentTeamId:null}});}return tx.contractExpirationRun.update({where:{id:run.id},data:{status:'COMPLETED',completedAt:new Date(),expiredCount:preview.expiredCount,activatedFutureCount:preview.activatedFutureCount,freeAgentCount:preview.freeAgentCount,resultHash:stableContractHash(preview.items)}});});}
export async function listExpirationRuns(){return{items:await prisma.contractExpirationRun.findMany({include:{worldSeason:true},orderBy:{createdAt:'desc'}})};}
export async function getExpirationRun(id:string){const item=await prisma.contractExpirationRun.findUnique({where:{id},include:{worldSeason:true,transactions:true}});if(!item)throw new ContractHttpError(404,'ContractExpirationRunNotFound','Expiration run not found');return item;}

export async function getContractReadiness(){const [meta,duplicateActive,mismatches,rights,ending,offers]=await Promise.all([prisma.appMeta.findUnique({where:{id:'default'}}),prisma.$queryRaw<Array<{playerId:string;count:number}>>`SELECT playerId, COUNT(*) count FROM PlayerContract WHERE status='ACTIVE' GROUP BY playerId HAVING COUNT(*) > 1`,prisma.$queryRaw<Array<{count:number}>>`SELECT COUNT(*) count FROM PlayerContract c JOIN Player p ON p.id=c.playerId WHERE c.status='ACTIVE' AND (p.currentTeamId IS NULL OR p.currentTeamId<>c.teamId)`,prisma.playerDraftRight.count({where:{status:'ACTIVE'}}),prisma.playerContract.count({where:{status:'ACTIVE'}}),prisma.contractOffer.count({where:{status:'SUBMITTED'}})]);const blockers=[] as string[],warnings=[] as string[];if(duplicateActive.length)blockers.push('Duplicate active contracts');if(Number(mismatches[0]?.count??0))blockers.push('Active contract ownership mismatch');if(!meta?.contractsInitializedAt)warnings.push('Compatibility contracts have not been initialized');if(rights)warnings.push(`${rights} rights-held prospects remain unsigned`);if(offers)warnings.push(`${offers} submitted offers await a decision`);return{status:blockers.length?'NOT_READY':warnings.length?'WARNING':'READY',checks:{initialized:Boolean(meta?.contractsInitializedAt),activeContracts:ending,pendingOffers:offers,rightsHeldProspects:rights},blockers,warnings};}
