/**
 * @fhm/engine — pure simulation/generation package (no I/O, no Fastify/Prisma/React).
 */

export const ENGINE_NAME = '@fhm/engine' as const;
export const ENGINE_VERSION = '0.1.0' as const;

/** Smoke-test helper proving the package builds and imports correctly. */
export function getEngineInfo(): { name: typeof ENGINE_NAME; version: typeof ENGINE_VERSION } {
  return { name: ENGINE_NAME, version: ENGINE_VERSION };
}

export {
  derivePlayerModel,
  deriveSkaterModel,
  deriveSkaterRole,
  deriveSkaterRatings,
  getHiddenPotential,
  PlayerModelValidationError,
  validateSkaterAttributes,
  validateGoalieAttributes,
  validateProfile,
  SKATER_ATTRIBUTE_KEYS,
  GOALIE_ATTRIBUTE_KEYS,
  PLAYER_MODEL_CONFIG,
} from './players/index.js';

export type * from './players/types.js';

export { deriveGoalieModel, deriveGoalieRole } from './goalies/index.js';
export { deriveGoalieRatings, computeRoleRating, weightedRating } from './players/ratings.js';

export {
  evaluateTeamReadiness,
  summarizeRoster,
  TEAM_READINESS_THRESHOLDS,
  isAvailableForReadiness,
  positionGroup,
} from './team-setup/index.js';

export type {
  TeamReadinessStatus,
  TeamReadinessRosterMember,
  TeamReadinessInput,
  TeamReadinessCheck,
  TeamReadinessCounts,
  TeamReadinessResult,
  RosterPositionGroup,
  TeamReadinessLineupPresence,
  TeamReadinessLineupSummary,
} from './team-setup/index.js';

export {
  LINEUP_SLOTS,
  LINEUP_REQUIRED_SLOT_COUNT,
  SLOT_REQUIRED_POSITION,
  SKATER_POSITIONS,
  isLineupSlot,
  isSkaterPosition,
  slotGroup,
  validateSecondaryPositions,
  positionFit,
  isEligibleForLineup,
  eligibilityRejectionReason,
  compareCandidates,
  validateLineup,
  generateAutoLineup,
  summarizeAutoLineupExplanation,
  summarizeValidation,
} from './lineups/index.js';

export type {
  LineupPosition,
  LineupRosterStatus,
  LineupModelStatus,
  LineupSlot,
  LineupValidationStatus,
  AutoLineupMode,
  LineupCandidate,
  LineupAssignmentInput,
  LineupValidationIssue,
  LineupValidationResult,
  AutoLineupExplanation,
  AutoLineupResult,
  LineupPresence,
  PositionFit,
  ValidateLineupInput,
  AutoLineupInput,
} from './lineups/index.js';

export {
  CHEMISTRY_CONFIG_VERSION,
  validateChemistryConfig,
  evaluateChemistryUnit,
  evaluateLineupChemistry,
  computeBaseAbility,
  computeEffectivePerformance,
  computeBaseCompatibility,
  roleCompatibilityScore,
  personalityCompatibilityScore,
  coachFitScore,
  tacticalFitScore,
  getRolePairScore,
  pairKey,
  chemistryLabel,
  summarizeUnitPlain,
  defaultChemistryRuntimeConfig,
  chemistryRuntimeFromBalance,
} from './chemistry/index.js';

export type {
  ChemistryCoachingStyle,
  ChemistryTacticalStyle,
  ChemistryPersonality,
  ChemistryUnitType,
  ChemistryLabel,
  ChemistryUnitStatus,
  ChemistryPlayerInput,
  ChemistryCoachInput,
  ChemistryContext,
  ChemistryFactor,
  ChemistryUnitResult,
  LineupChemistrySummary,
  EvaluateUnitInput,
  LineupChemistryInput,
  ChemistryRuntimeConfig,
} from './chemistry/index.js';

export {
  BALANCE_SCHEMA_VERSION,
  balanceConfigSchema,
  runtimeSimulationSettingsSchema,
  validateBalanceConfig,
  parseBalanceConfig,
  validateRuntimeSimulationSettings,
  getStandardBalanceConfig,
  defaultRuntimeSimulationSettings,
  canonicalizeBalanceConfig,
  normalizeBalanceConfig,
  sortJsonValue,
  collectChangedPaths,
  isF11CompatibleBalanceConfig,
  isF12CompatibleBalanceConfig,
  isF13CompatibleBalanceConfig,
  isF14CompatibleBalanceConfig,
  BALANCE_SCHEMA_VERSIONS,
  PENALTY_INFRACTIONS,
  SHOT_TYPES,
  defaultShotsSection,
  defaultGoaliesSection,
  defaultPenaltiesSection,
  defaultMatchCompletionSection,
} from './balance/index.js';

export type {
  BalanceConfig,
  BalanceValidationIssue,
  BalanceValidationResult,
  RuntimeSimulationSettings,
  LoggingLevel,
  ChemistryBalanceSection,
  PlayerModelBalanceSection,
  MatchBalanceSection,
  ShotsBalanceSection,
  GoaliesBalanceSection,
  PenaltiesBalanceSection,
  MatchCompletionBalanceSection,
  PenaltyInfraction,
  ShotType,
} from './balance/index.js';

export {
  FHM_ENGINE_VERSION,
  F13_SIMULATION_MODE,
  F14_SIMULATION_MODE,
  F12_SIMULATION_MODE,
  F12_ENGINE_VERSION,
  F11_ENGINE_VERSION,
  F11_SIMULATION_MODE,
  SNAPSHOT_SCHEMA_VERSION,
  REGULATION_PERIODS,
  PERIOD_DURATION_SECONDS,
  OVERTIME_DURATION_SECONDS,
  MINOR_PENALTY_SECONDS,
  FORBIDDEN_F14_EVENT_TYPES,
  FORBIDDEN_F13_EVENT_TYPES,
  FORBIDDEN_F11_EVENT_TYPES,
  SUPPORTED_STRENGTH_STATES,
  validateSimulationInput,
  canonicalizeSimulationInput,
  getMatchConfig,
  getPenaltiesConfig,
  createRng,
  restoreRng,
  nextFloat,
  nextInt,
  chance,
  pick,
  weightedPick,
  createInitialMatchState,
  simulateNextEvent,
  simulateUntil,
  simulateRegulation,
  simulateCompleteMatch,
  simulateStep,
  computeDiagnostics,
  serializeMatchSnapshot,
  restoreMatchSnapshot,
  computeTraceHash,
  createShotAttempt,
  resolvePendingShot,
  computeShotOpportunityProbability,
  deriveAssists,
  reduceStatistics,
  reconcileStatistics,
  InvalidSimulationInputError,
  IncompatibleBalanceConfigError,
  InvalidSnapshotError,
  SafetyLimitExceededError,
  IllegalStateTransitionError,
  StatisticsReconciliationError,
  SimulationError,
} from './simulation/index.js';

export type {
  SimulationInput,
  SimulationTeamInput,
  SimulationPlayerProfile,
  SimulationBalanceRef,
  RegulationRules,
  MatchState,
  MatchEvent,
  MatchEventType,
  MatchSnapshot,
  SimulationResult,
  CompleteSimulationResult,
  FinalMatchResult,
  MatchCompletionRules,
  CompleteMatchResult,
  SimulationDiagnostics,
  MatchStatistics,
  PlayerSkaterStats,
  PlayerGoalieStats,
  TeamStats,
  PeriodScore,
  PendingShot,
  ReconciliationResult,
  StepMode,
  StepResult,
  EventDetailLevel,
  PossessionSide,
  PossessionZone,
  SimulationStatus,
  ActiveLines,
  StrengthState,
  ActivePenalty,
  GoalStrength,
  PenaltyEndReason,
} from './simulation/index.js';

export {
  deriveGameSeed,
  deriveGameSeeds,
  resolveSideOrientation,
  toLabGameSummary,
  enrichPlayerNames,
  reduceGameSummaries,
  createEmptyAggregate,
  detectLabAnomalies,
  compareLabAggregates,
  computeBatchHash,
  runLabBatch,
  SUPPORTED_LAB_COUNTS,
  DEFAULT_LAB_ANOMALY_GUARDRAILS,
  COMBINED_GOALS_HISTOGRAM_BUCKETS,
} from './simulation/index.js';

export type {
  LabSimulationCount,
  LabSideMode,
  LabWinner,
  LabDecisionType,
  LabGameSummary,
  LabAggregate,
  LabAnomaly,
  LabBatchResult,
  LabBatchRunOptions,
  LabBatchRunOutput,
  LabComparisonResult,
  LabAnomalyGuardrails,
  LabPlayerAggregate,
  LabUnitAggregate,
} from './simulation/index.js';

export { buildTestSimulationInput } from './simulation/match/fixture.js';

export {
  COMPETITION_RULES_SCHEMA_VERSION,
  COMPETITION_RULES_TEMPLATE_KEYS,
  CompetitionValidationError,
  getCompetitionRulesTemplate,
  defaultMatchRulesSection,
  defaultPointsRules,
  canonicalizeCompetitionRules,
  normalizeCompetitionRules,
  validateCompetitionRules,
  parseCompetitionRulesJson,
  toMatchCompletionRules,
  validateStageConfig,
  canonicalizeStageConfig,
  validateStageDependencyGraph,
  validateStageParticipantSource,
  validateHomePattern,
  hashCompetitionRules,
  hashStageConfig,
  listAllowedEditionTransitions,
  canTransitionEditionStatus,
  assertEditionTransition,
  isEditionStructurallyEditable,
  assertEditionStructurallyEditable,
  transitionRequiresReadiness,
  evaluateEditionReadiness,
  assertCanActivateOrReady,
  defaultRegularSeasonConfig,
  parseRegularSeasonConfig,
  toStageConfigJson,
  generateRegularSeasonSchedule,
  deriveMatchSimulationSeed,
  normalizeParticipantIds,
  computeStandings,
  reconcileStandingsBasics,
  aggregateTeamSeasonStats,
  aggregatePlayerSeasonStats,
  buildQualificationPreview,
  RegularSeasonError,
} from './competitions/index.js';

export type {
  CompetitionRulesFormat,
  TiebreakerCode,
  CompetitionRulesTemplateKey,
  CompetitionPointsRules,
  CompetitionMatchRulesSection,
  CompetitionQualificationRules,
  CompetitionSeriesRules,
  CompetitionRules,
  CompetitionStageType,
  StageParticipantSource,
  CompetitionEditionStatus,
  CompetitionStageStatus,
  CompetitionParticipantStatus,
  CompetitionParticipantSource,
  RegularSeasonStageConfig,
  RoundRobinStageConfig,
  GroupStageConfig,
  KnockoutStageConfig,
  BestOfSeriesStageConfig,
  FinalRankingStageConfig,
  StageConfig,
  CompetitionStageDefinition,
  CompetitionParticipantDefinition,
  EditionStructureInput,
  ReadinessOverall,
  ReadinessCheckSeverity,
  ReadinessCheck,
  EditionReadinessResult,
  RegularSeasonScheduleFormat,
  HomeAwayMode,
  RegularSeasonConfig,
  ScheduledMatchSpec,
  ScheduleRound,
  ScheduleDiagnostics,
  GeneratedSchedule,
  MatchDecisionForStandings,
  StandingMatchResult,
  StandingParticipant,
  StandingRow,
  StandingsResult,
  TeamSeasonStatRow,
  PlayerSeasonStatRow,
  MatchTeamStatSummary,
  MatchPlayerStatSummary,
} from './competitions/index.js';
