import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { areCommissionerWritesEnabled, hasCommissionerHeader } from '../commissioner/gate.js';
import { CommissionerHttpError, commissionerErrorBody } from '../commissioner/errors.js';
import { detailResponse, listResponse } from '../http.js';
import { ContractHttpError } from '../services/contract-errors.js';
import { listContractConfigurations } from '../services/contract-config.js';
import { prisma } from '../db/client.js';
import { acceptOffer, executeExpiration, executeInitialContracts, expirationPreview, prepareExpiration, prepareInitialContracts, previewInitialContracts, rejectOffer, releaseContract } from '../services/contracts.js';
import { activateContractVersion, auditContractAction, createContractPreset, createContractVersion } from '../services/commissioner-contracts.js';
function access(q:any){if(!hasCommissionerHeader(q.headers))throw new CommissionerHttpError(403,'CommissionerModeRequired','Commissioner Mode header is required');if(!areCommissionerWritesEnabled())throw new CommissionerHttpError(403,'CommissionerWritesDisabled','Commissioner writes are disabled');}
function error(r:any,e:unknown){if(e instanceof CommissionerHttpError)return r.status(e.statusCode).send(commissionerErrorBody(e));if(e instanceof ContractHttpError)return r.status(e.statusCode).send({error:e.code,message:e.message,details:e.details});if(e instanceof z.ZodError)return r.status(400).send({error:'InvalidContractRequest',message:'Invalid contract request',details:e.issues});throw e;}
const reason=z.string().trim().min(1).max(500),source=(q:any):'COMMISSIONER_UI'|'COMMISSIONER_API'=>q.headers['x-fhm-commissioner-source']==='ui'?'COMMISSIONER_UI':'COMMISSIONER_API';
export async function registerCommissionerContractRoutes(app:FastifyInstance){
  app.get('/api/commissioner/contracts/diagnostics',async(q,r)=>{try{access(q);const [contracts,offers,rights]=await Promise.all([prisma.playerContract.findMany({orderBy:{createdAt:'desc'},take:100}),prisma.contractOffer.findMany({orderBy:{createdAt:'desc'},take:100}),prisma.playerDraftRight.findMany({where:{status:'ACTIVE'},take:100})]);return detailResponse({contracts,offers,rights,noSalaryCap:true,noTrades:true})}catch(e){return error(r,e)}});
  app.get('/api/commissioner/contracts/:contractId/diagnostics',async(q,r)=>{try{access(q);const item=await prisma.playerContract.findUnique({where:{id:(q.params as any).contractId},include:{player:true,team:true,originatingOffer:true,originatingDraftRight:true,transactions:true}});if(!item)throw new ContractHttpError(404,'ContractNotFound','Contract not found');return detailResponse(item)}catch(e){return error(r,e)}});
  app.get('/api/commissioner/contracts/configurations',async(q,r)=>{try{access(q);return listResponse(await listContractConfigurations(prisma))}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/initial-preview',async(q,r)=>{try{access(q);const b=z.object({worldSeasonId:z.string().min(1)}).parse(q.body);return detailResponse(await previewInitialContracts(b.worldSeasonId))}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/initial-prepare',async(q,r)=>{try{access(q);const b=z.object({worldSeasonId:z.string().min(1),reason}).parse(q.body);const item=await prepareInitialContracts(b.worldSeasonId,b.reason,source(q));await auditContractAction('PLAYER_CONTRACT',item.id,'INITIAL_CONTRACTS_PREPARED',b.reason,item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/initial-runs/:runId/execute',async(q,r)=>{try{access(q);const b=z.object({reason:reason.optional()}).parse(q.body??{});const item=await executeInitialContracts((q.params as any).runId);await auditContractAction('PLAYER_CONTRACT',item.id,'INITIAL_CONTRACTS_CREATED',b.reason??'Execute prepared initial contracts',item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/expiration-preview',async(q,r)=>{try{access(q);const b=z.object({worldSeasonId:z.string().min(1)}).parse(q.body);return detailResponse(await expirationPreview(b.worldSeasonId))}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/expiration-prepare',async(q,r)=>{try{access(q);const b=z.object({worldSeasonId:z.string().min(1),reason}).parse(q.body);const item=await prepareExpiration(b.worldSeasonId,b.reason,source(q));await auditContractAction('CONTRACT_EXPIRATION_RUN',item.id,'CONTRACT_EXPIRATION_PREPARED',b.reason,item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/expiration-runs/:runId/execute',async(q,r)=>{try{access(q);const item=await executeExpiration((q.params as any).runId);await auditContractAction('CONTRACT_EXPIRATION_RUN',item.id,'CONTRACT_EXPIRATION_COMPLETED','Execute prepared expiration',item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contract-offers/:offerId/accept',async(q,r)=>{try{access(q);const b=z.object({reason,expectedUpdatedAt:z.string().datetime().optional()}).parse(q.body);const item=await acceptOffer((q.params as any).offerId,b.reason,b.expectedUpdatedAt);await auditContractAction('CONTRACT_OFFER',(q.params as any).offerId,'CONTRACT_OFFER_ACCEPTED',b.reason,item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contract-offers/:offerId/reject',async(q,r)=>{try{access(q);const b=z.object({reason,expectedUpdatedAt:z.string().datetime().optional()}).parse(q.body);const item=await rejectOffer((q.params as any).offerId,b.reason,b.expectedUpdatedAt);await auditContractAction('CONTRACT_OFFER',(q.params as any).offerId,'CONTRACT_OFFER_REJECTED',b.reason,item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contracts/:contractId/release',async(q,r)=>{try{access(q);const b=z.object({reason,expectedUpdatedAt:z.string().datetime().optional()}).parse(q.body);const item=await releaseContract((q.params as any).contractId,undefined,b);await auditContractAction('PLAYER_CONTRACT',item.id,'PLAYER_RELEASED',b.reason,item,source(q));return detailResponse(item)}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contract-configurations',async(q,r)=>{try{access(q);const b=z.object({name:z.string().min(1),description:z.string().nullable().optional(),config:z.unknown(),activate:z.boolean().optional(),reason}).parse(q.body);return detailResponse(await createContractPreset(b,source(q)))}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contract-configurations/:presetId/versions',async(q,r)=>{try{access(q);const b=z.object({config:z.unknown(),activate:z.boolean().optional(),reason}).parse(q.body);return detailResponse(await createContractVersion((q.params as any).presetId,b,source(q)))}catch(e){return error(r,e)}});
  app.post('/api/commissioner/contract-configuration-versions/:versionId/activate',async(q,r)=>{try{access(q);const b=z.object({reason}).parse(q.body);return detailResponse(await activateContractVersion((q.params as any).versionId,b.reason,source(q)))}catch(e){return error(r,e)}});
}
